name: Go
on: [push]

env:
  GOCACHE: "/home/runner/go/cache"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          /home/runner/go/cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go
    - name: Print Go Version
      run: go version

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
        then
          find . -iname '*.go' | xargs gofmt -d
          exit 1
        fi

    - name: Vet
      run: go vet ./...

    - name: Install staticcheck
      run: go get honnef.co/go/tools/cmd/staticcheck

    - name: Run staticcheck
      run: staticcheck ./...